//////////////////////////////////////////////////////////////////////////////
//
// Include file generated by Anders Melander's Resource Editor
//
//////////////////////////////////////////////////////////////////////////////


#define APSTUDIO_READONLY_SYMBOLS
#include "sdkddkver.h"
#include "winresrc.h"
#undef APSTUDIO_READONLY_SYMBOLS


//////////////////////////////////////////////////////////////////////////////
//
// Symbol definitions
//

#define LANG_SCOTTISH_GAELIC            0x91
#define SUBLANG_SCOTTISH_GAELIC         0x01
#define SUBLANG_SERBIAN_MONTENEGRO_LATIN 0x0b
#define SUBLANG_SERBIAN_MONTENEGRO_CYRILLIC 0x0c
#define SUBLANG_SERBIAN_SERBIA_LATIN    0x09
#define SUBLANG_SERBIAN_SERBIA_CYRILLIC 0x0a
