
#define S_DISKETTENAME      LS(100)
#define S_FLASHNAME         LS(101)
#define S_CDROMNAME         LS(102)
#define S_USERFOLDERNAME    LS(103)
#define S_USERFOLDERNAME1   LS(104)
#define S_USERFOLDERNAMEN   LS(105)
#define S_STUDENTFOLDERNAME     LS(106)
#define S_STUDENTNAME           LS(107)
#define S_NOTEPAD           LS(108)
#define S_MEDIAPLAYER       LS(109)
#define S_DISKSELECT1       LS(110)
#define S_DISKSELECT2       LS(111)
#define S_SAVERESTRICT      LS(112)
#define S_RESTRICT          LS(113)
#define S_RESEMPTY          LS(114)
#define S_RESSTUDENTEMPTY       LS(115)
#define S_RUNPROTECT        LS(116)

