// Do not edit. This file is machine generated by the Resource DLL Wizard.

library test;

{ITE} {LCID:00000419:00000409} {}
{ITE} {RCFileType} {test_DRC.rc}

{$R 'test_DRC.res' 'test_DRC.rc'}

{$E ENU}

begin
end.